/**
 * Subject-banded paper structure.
 *
 * A banded paper pins an exact subject to an exact run of question numbers
 * (EAMCET: 1-40 Physics, 41-80 Chemistry, 81-160 Mathematics). The band ranges
 * are derived from the declared counts rather than supplied by the caller, so
 * the ranges can never disagree with each other or leave a gap.
 *
 * Pure module — no server imports, safe to use from the client paper view and
 * from the generation server function alike.
 */

export type QuestionTypeCounts = {
  mcq: number;
  numeric: number;
  short: number;
  long: number;
};

/** A declared subject band: how many questions, for which subject. */
export type SubjectSection = {
  subject: string;
  questionCount: number;
};

export type ResolvedSection = SubjectSection & {
  /** 1-based inclusive first and last printed question numbers. */
  firstQuestion: number;
  lastQuestion: number;
};

export const MAX_SUBJECT_SECTIONS = 10;

/**
 * Turn declared band counts into contiguous 1-based ranges.
 *
 * Throws if the counts do not add up, because a paper with a gap in its
 * numbering cannot be printed, keyed or bubbled consistently.
 */
export function resolveSectionRanges(sections: SubjectSection[]): ResolvedSection[] {
  let cursor = 1;
  return sections.map((section) => {
    const count = Math.max(0, Math.floor(Number(section.questionCount) || 0));
    const first = cursor;
    const last = cursor + count - 1;
    cursor = last + 1;
    return { ...section, questionCount: count, firstQuestion: first, lastQuestion: last };
  });
}

export function sectionTotal(sections: SubjectSection[]): number {
  return sections.reduce(
    (sum, s) => sum + (Math.max(0, Math.floor(Number(s.questionCount) || 0)) || 0),
    0,
  );
}

/**
 * Split a whole-paper type distribution across the subject bands.
 *
 * Each band is generated by its own model call, so every band needs its own
 * type blueprint. Counts are shared out proportionally to band size using the
 * largest-remainder method, which guarantees the per-band counts sum to exactly
 * the band size *and* the bands together reproduce the original distribution
 * exactly — a naive per-type `Math.round` would drift and silently change the
 * paper's total marks.
 */
export function allocateSectionDistributions(
  total: QuestionTypeCounts,
  sectionCounts: number[],
): QuestionTypeCounts[] {
  const grand = total.mcq + total.numeric + total.short + total.long;
  const bandSum = sectionCounts.reduce((a, b) => a + b, 0);
  if (grand <= 0) throw new Error("Cannot allocate a paper with no questions.");
  if (bandSum !== grand) {
    throw new Error(
      `Subject sections cover ${bandSum} questions but the blueprint defines ${grand}.`,
    );
  }

  const types = ["mcq", "numeric", "short", "long"] as const;

  return sectionCounts.map((count) => {
    if (count === 0) return { mcq: 0, numeric: 0, short: 0, long: 0 };

    // Exact proportional share of every type for this band.
    const exact = types.map((type) => (total[type] * count) / grand);
    const base = exact.map((value) => Math.floor(value));
    let assigned = base.reduce((a, b) => a + b, 0);

    // Hand the leftover slots to the types with the largest fractional part.
    const order = exact
      .map((value, index) => ({ index, remainder: value - base[index]! }))
      .sort((a, b) => b.remainder - a.remainder || a.index - b.index);

    for (const { index } of order) {
      if (assigned >= count) break;
      base[index] = base[index]! + 1;
      assigned += 1;
    }

    return {
      mcq: base[0]!,
      numeric: base[1]!,
      short: base[2]!,
      long: base[3]!,
    };
  });
}

/** Marks a distribution is worth given per-type mark weights. */
export function distributionMarks(
  distribution: QuestionTypeCounts,
  marks: QuestionTypeCounts,
): number {
  return (
    distribution.mcq * marks.mcq +
    distribution.numeric * marks.numeric +
    distribution.short * marks.short +
    distribution.long * marks.long
  );
}

/** How many questions a distribution contains. */
export function distributionTotal(distribution: QuestionTypeCounts): number {
  return distribution.mcq + distribution.numeric + distribution.short + distribution.long;
}

/**
 * Split a question count into call-sized batches of near-equal size.
 *
 * A band is far too large to ask for in one response (EAMCET Mathematics alone
 * is 80 questions), and a truncated JSON response is rejected outright rather
 * than repaired, so bands are generated in batches. The remainder is spread
 * over the first batches instead of leaving one of them a single question, which
 * keeps every batch worth its own call and stops the odd batch from distorting
 * the per-batch type mix.
 */
export function chunkQuestionCounts(count: number, maxPerCall: number): number[] {
  const total = Math.max(0, Math.floor(Number(count) || 0));
  const max = Math.max(1, Math.floor(Number(maxPerCall) || 1));
  const calls = Math.ceil(total / max);
  if (calls === 0) return [];
  const base = Math.floor(total / calls);
  const extra = total % calls;
  return Array.from({ length: calls }, (_, index) => base + (index < extra ? 1 : 0));
}
