/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin/login'
import { Route as SuperAdminBootstrapRouteImport } from './routes/super-admin/bootstrap'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSyllabiRouteImport } from './routes/_authenticated/syllabi'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedSuperAdminIndexRouteImport } from './routes/_authenticated/super-admin/index'
import { Route as AuthenticatedPapersIndexRouteImport } from './routes/_authenticated/papers/index'
import { Route as AuthenticatedSuperAdminOrganizationsRouteImport } from './routes/_authenticated/super-admin/organizations'
import { Route as AuthenticatedSuperAdminCreditsRouteImport } from './routes/_authenticated/super-admin/credits'
import { Route as AuthenticatedPapersNewRouteImport } from './routes/_authenticated/papers/new'
import { Route as AuthenticatedPapersIdRouteImport } from './routes/_authenticated/papers/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/super-admin/login',
  path: '/super-admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminBootstrapRoute = SuperAdminBootstrapRouteImport.update({
  id: '/super-admin/bootstrap',
  path: '/super-admin/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSyllabiRoute = AuthenticatedSyllabiRouteImport.update({
  id: '/syllabi',
  path: '/syllabi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminIndexRoute =
  AuthenticatedSuperAdminIndexRouteImport.update({
    id: '/super-admin/',
    path: '/super-admin/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPapersIndexRoute =
  AuthenticatedPapersIndexRouteImport.update({
    id: '/papers/',
    path: '/papers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminOrganizationsRoute =
  AuthenticatedSuperAdminOrganizationsRouteImport.update({
    id: '/super-admin/organizations',
    path: '/super-admin/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminCreditsRoute =
  AuthenticatedSuperAdminCreditsRouteImport.update({
    id: '/super-admin/credits',
    path: '/super-admin/credits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPapersNewRoute = AuthenticatedPapersNewRouteImport.update({
  id: '/papers/new',
  path: '/papers/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPapersIdRoute = AuthenticatedPapersIdRouteImport.update({
  id: '/papers/$id',
  path: '/papers/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/syllabi': typeof AuthenticatedSyllabiRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/super-admin/bootstrap': typeof SuperAdminBootstrapRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/papers/$id': typeof AuthenticatedPapersIdRoute
  '/papers/new': typeof AuthenticatedPapersNewRoute
  '/super-admin/credits': typeof AuthenticatedSuperAdminCreditsRoute
  '/super-admin/organizations': typeof AuthenticatedSuperAdminOrganizationsRoute
  '/papers/': typeof AuthenticatedPapersIndexRoute
  '/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/syllabi': typeof AuthenticatedSyllabiRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/super-admin/bootstrap': typeof SuperAdminBootstrapRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/papers/$id': typeof AuthenticatedPapersIdRoute
  '/papers/new': typeof AuthenticatedPapersNewRoute
  '/super-admin/credits': typeof AuthenticatedSuperAdminCreditsRoute
  '/super-admin/organizations': typeof AuthenticatedSuperAdminOrganizationsRoute
  '/papers': typeof AuthenticatedPapersIndexRoute
  '/super-admin': typeof AuthenticatedSuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/syllabi': typeof AuthenticatedSyllabiRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/super-admin/bootstrap': typeof SuperAdminBootstrapRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/_authenticated/papers/$id': typeof AuthenticatedPapersIdRoute
  '/_authenticated/papers/new': typeof AuthenticatedPapersNewRoute
  '/_authenticated/super-admin/credits': typeof AuthenticatedSuperAdminCreditsRoute
  '/_authenticated/super-admin/organizations': typeof AuthenticatedSuperAdminOrganizationsRoute
  '/_authenticated/papers/': typeof AuthenticatedPapersIndexRoute
  '/_authenticated/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/dashboard'
    | '/syllabi'
    | '/templates'
    | '/super-admin/bootstrap'
    | '/super-admin/login'
    | '/papers/$id'
    | '/papers/new'
    | '/super-admin/credits'
    | '/super-admin/organizations'
    | '/papers/'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/dashboard'
    | '/syllabi'
    | '/templates'
    | '/super-admin/bootstrap'
    | '/super-admin/login'
    | '/papers/$id'
    | '/papers/new'
    | '/super-admin/credits'
    | '/super-admin/organizations'
    | '/papers'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/change-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/syllabi'
    | '/_authenticated/templates'
    | '/super-admin/bootstrap'
    | '/super-admin/login'
    | '/_authenticated/papers/$id'
    | '/_authenticated/papers/new'
    | '/_authenticated/super-admin/credits'
    | '/_authenticated/super-admin/organizations'
    | '/_authenticated/papers/'
    | '/_authenticated/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SuperAdminBootstrapRoute: typeof SuperAdminBootstrapRoute
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/login': {
      id: '/super-admin/login'
      path: '/super-admin/login'
      fullPath: '/super-admin/login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/bootstrap': {
      id: '/super-admin/bootstrap'
      path: '/super-admin/bootstrap'
      fullPath: '/super-admin/bootstrap'
      preLoaderRoute: typeof SuperAdminBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/syllabi': {
      id: '/_authenticated/syllabi'
      path: '/syllabi'
      fullPath: '/syllabi'
      preLoaderRoute: typeof AuthenticatedSyllabiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/': {
      id: '/_authenticated/super-admin/'
      path: '/super-admin'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AuthenticatedSuperAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/papers/': {
      id: '/_authenticated/papers/'
      path: '/papers'
      fullPath: '/papers/'
      preLoaderRoute: typeof AuthenticatedPapersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/organizations': {
      id: '/_authenticated/super-admin/organizations'
      path: '/super-admin/organizations'
      fullPath: '/super-admin/organizations'
      preLoaderRoute: typeof AuthenticatedSuperAdminOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/credits': {
      id: '/_authenticated/super-admin/credits'
      path: '/super-admin/credits'
      fullPath: '/super-admin/credits'
      preLoaderRoute: typeof AuthenticatedSuperAdminCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/papers/new': {
      id: '/_authenticated/papers/new'
      path: '/papers/new'
      fullPath: '/papers/new'
      preLoaderRoute: typeof AuthenticatedPapersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/papers/$id': {
      id: '/_authenticated/papers/$id'
      path: '/papers/$id'
      fullPath: '/papers/$id'
      preLoaderRoute: typeof AuthenticatedPapersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSyllabiRoute: typeof AuthenticatedSyllabiRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedPapersIdRoute: typeof AuthenticatedPapersIdRoute
  AuthenticatedPapersNewRoute: typeof AuthenticatedPapersNewRoute
  AuthenticatedSuperAdminCreditsRoute: typeof AuthenticatedSuperAdminCreditsRoute
  AuthenticatedSuperAdminOrganizationsRoute: typeof AuthenticatedSuperAdminOrganizationsRoute
  AuthenticatedPapersIndexRoute: typeof AuthenticatedPapersIndexRoute
  AuthenticatedSuperAdminIndexRoute: typeof AuthenticatedSuperAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSyllabiRoute: AuthenticatedSyllabiRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedPapersIdRoute: AuthenticatedPapersIdRoute,
  AuthenticatedPapersNewRoute: AuthenticatedPapersNewRoute,
  AuthenticatedSuperAdminCreditsRoute: AuthenticatedSuperAdminCreditsRoute,
  AuthenticatedSuperAdminOrganizationsRoute:
    AuthenticatedSuperAdminOrganizationsRoute,
  AuthenticatedPapersIndexRoute: AuthenticatedPapersIndexRoute,
  AuthenticatedSuperAdminIndexRoute: AuthenticatedSuperAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SuperAdminBootstrapRoute: SuperAdminBootstrapRoute,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
